### ISSUE TITLE
Use of translations and selectable admins

### ISSUE THREAD

**Issue by ayacoo** [eid-login/eid-login-typo3#3]
Disclaimer: I know it's a first version ;-)

https://github.com/eid-login/eid-login-typo3/blob/master/Classes/Command/CertificateRolloverCommand.php

For more acceptance, it would be good to make the people selectable. In addition, the mail text should not be hard-coded in the file. We should use the possibility of language files.

**Comment by 7118path** [comment]
We are very sorry, but for a mail that will be sent once every two years, it seems sufficient for us to send it in English to all admins.
